# NDVI Timelapse — WORLD_REGIONS and COUNTRIES (as in the reference app)
# WORLD_REGIONS (short list)
WORLD_REGIONS = [
    "Africa",
    "E Asia",
    "Europe",
    "N Asia",
    "S Asia",
    "Oceania",
    "SE Asia",
    "SW Asia",
    "Australia",
    "Caribbean",
    "Antarctica",
    "S Atlantic",
    "Central Asia",
    "Indian Ocean",
    "North America",
    "South America",
    "Central America"
]

# COUNTRIES (long list; copied from the reference, order preserved)
COUNTRIES = ['Abyei Area',
 'Afghanistan',
 'Akrotiri',
 'Aksai Chin',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Anguilla',
 'Antarctica',
 'Antigua & Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Ashmore & Cartier Is',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas, The',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bir Tawil',
 'Bolivia',
 'Bosnia & Herzegovina',
 'Botswana',
 'Bouvet Island',
 'Brazil',
 'British Indian Ocean Terr',
 'British Virgin Is',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burma',
 'Burundi',
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cayman Is',
 'Central African Rep',
 'Chad',
 'Chile',
 'China',
 'Christmas I',
 'Clipperton Island',
 'Cocos (Keeling) Is',
 'Colombia',
 'Comoros',
 'Cook Is',
 'Coral Sea Is',
 'Costa Rica',
 "Cote d'Ivoire",
 'Croatia',
 'Cuba',
 'Curacao',
 'Cyprus',
 'Czechia',
 'Dem Rep of the Congo',
 'Demchok Area',
 'Denmark',
 'Dhekelia',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Dragonja River Mouth',
 'Dramana-Shakatoe Area',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Falkland Islands',
 'Faroe Is',
 'Fed States of Micronesia',
 'Fiji',
 'Finland',
 'France',
 'French Guiana',
 'French Polynesia',
 'French S & Antarctic Lands',
 'Gabon',
 'Gambia, The',
 'Gaza Strip',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Greenland',
 'Grenada',
 'Guadeloupe',
 'Guam',
 'Guatemala',
 'Guernsey',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Halaib Triangle',
 'Heard I & McDonald Is',
 'Honduras',
 'Hong Kong',
 'Hungary',
 'IN-CH Small Disputed Areas',
 'Iceland',
 'India',
 'Indonesia',
 'Invernada Area',
 'Iran',
 'Iraq',
 'Ireland',
 'Isla Brasilera',
 'Isle of Man',
 'Israel',
 'Italy',
 'Jamaica',
 'Jan Mayen',
 'Japan',
 'Jersey',
 'Jordan',
 'Kalapani Area',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Korea, North',
 'Korea, South',
 'Korean Is. (UN Jurisdiction)',
 'Kosovo',
 'Koualou Area',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liancourt Rocks',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macau',
 'Macedonia',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Is',
 'Martinique',
 'Mauritania',
 'Mauritius',
 'Mayotte',
 'Mexico',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Namibia',
 'Nauru',
 'Navassa I',
 'Nepal',
 'Netherlands',
 'Netherlands (Caribbean)',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Niue',
 "No Man's Land",
 'Norfolk I',
 'Northern Mariana Is',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Panama',
 'Papua New Guinea',
 'Paracel Is',
 'Paraguay',
 'Peru',
 'Philippines',
 'Pitcairn Is',
 'Poland',
 'Portugal',
 'Portugal (Azores)',
 'Portugal (Madeira Is)',
 'Puerto Rico',
 'Qatar',
 'Rep of the Congo',
 'Reunion',
 'Romania',
 'Russia',
 'Rwanda',
 'S Georgia & S Sandwich Is',
 'Saint Lucia',
 'Samoa',
 'San Marino',
 'Sao Tome & Principe',
 'Saudi Arabia',
 'Senegal',
 'Senkakus',
 'Serbia',
 'Seychelles',
 'Siachen-Saltoro Area',
 'Sierra Leone',
 'Sinafir & Tiran Is.',
 'Singapore',
 'Sint Maarten',
 'Slovakia',
 'Slovenia',
 'Solomon Is',
 'Somalia',
 'South Africa',
 'South Sudan',
 'Spain',
 'Spain (Africa)',
 'Spain (Canary Is)',
 'Spratly Is',
 'Sri Lanka',
 'St Barthelemy',
 'St Helena',
 'St Kitts & Nevis',
 'St Martin',
 'St Pierre & Miquelon',
 'St Vincent & the Grenadines',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tokelau',
 'Tonga',
 'Trinidad & Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turks & Caicos Is',
 'Tuvalu',
 'US Minor Pacific Is. Refuges',
 'US Virgin Is',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'United States (Alaska)',
 'United States (Hawaii)',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Vatican City',
 'Venezuela',
 'Vietnam',
 'Wake I',
 'Wallis & Futuna',
 'West Bank',
 'Western Sahara',
 'Yemen',
 'Zambia',
 'Zimbabwe']
